#!/bin/sh
command=$@
output=$(${command} 2>&1)
return_code=$?
if [ "${return_code}" -ge 4 -a "${return_code}" -le 255 ]; then
  return_code=3
fi
echo ${output} | /bin/grep -qi "Socket timeout" && return_code=3
echo ${output}
exit ${return_code}
