#!/bin/bash

while getopts "s:n:i:w:c:wl:cl" opts; do
  case "${opts}" in
    s) sensor="${OPTARG}";;
    n) name="${OPTARG}";;
    i) id="${OPTARG}";;
    w) warn="${OPTARG}";;
    c) crit="${OPTARG}";;
    wl) warn_low="${OPTARG}";;
    cl) crit_low="${OPTARG}";;
  esac
done

test "${sensor}x" = "x" && sensor=""

status="$(/usr/bin/sensors -f ${sensor} 2>&1 | /bin/grep -E "${id}|not found")"
if echo "$status" | /bin/grep -iq "specified sensor(s) not found"; then
  echo "CRITICAL: ${status}"
  exit 2
fi
full_temp="$(echo "${status}" \
    | /bin/sed -n 's/.*:[ ]\++\([0-9]\+\.[0-9]\+\).F.*/\1/p')"
temp="$(printf "%.0f" "$full_temp")"

if [ "${temp}" -gt "${crit}" ]; then
  echo "CRITICAL: ${name} temperature: ${temp}°F, above critical threshold of ${crit}°F!"
  exit 2
elif [ "${temp}" -gt "${warn}" ]; then
  echo "WARNING: ${name} temperature: ${temp}°F, above warning threshold of ${warn}°F!"
  exit 1
elif [ "${temp}" -lt "${crit_low}" ]; then
  echo "CRITICAL: ${name} temperature: ${temp}°F, below critical threshold of ${crit}°F!"
  exit 2
elif [ "${temp}" -lt "${warn_low}" ]; then
  echo "WARNING: ${name} temperature: ${temp}°F, below warning threshold of ${warn}°F!"
  exit 1
else
  echo "OK: ${name} Temperature: ${temp}°F"
  exit 0
fi
