#!/usr/bin/python3


import argparse
import subprocess
import sys

exit = 2
status = 'CRITICAL'
verification = ''
verify_passed = True

parser = argparse.ArgumentParser()
parser.add_argument('--host', help='Hostname of the service to check.')
parser.add_argument('--port', help='Port number to check', default='443')
parser.add_argument('--server', help='Hostname of the server to connect to.')
args = parser.parse_args()
if not args.server:
  args.server = args.host
if not all([args.host, args.port, args.server]):
  parser.error('Please specify all args.')

cmd = ['openssl', 's_client', '-connect', f'{args.host}:{args.port}',
       '-servername', args.server]
print(' '.join(cmd))
p = subprocess.Popen(cmd, stdin=subprocess.DEVNULL, stdout=subprocess.PIPE,
                     stderr=subprocess.PIPE, universal_newlines=True)
stdout, stderr = p.communicate()

for line in stderr.splitlines():
  if line.startswith('verify'):
    if line != 'verify return:1':
      verify_passed = False

for line in stdout.splitlines():
  if 'verif' in line.lower():
    verification = line.strip()

if verification != 'Verify return code: 0 (ok)':
  verify_passed = False

if verify_passed:
  exit = 0
  status = 'OK'

print(f'CERT CHAIN {status}: {verification}\n{stderr.rstrip()}')
sys.exit(exit)
