#!/bin/bash
warning=24
critical=72

currentDate=$(date "+%s")

while getopts "d:w:c:" optionName; do
  case "$optionName" in
    s) statusfile="$OPTARG";;
    w) warning=$OPTARG;;
    c) critical=$OPTARG;;
  esac
done

# check to see if the statusfile exists
if ! [ -r "$statusfile" ]; then
  printf "CRITICAL - the borgbackup statusfile you pointed to does not exist! - %s\n" "$statusfile"
  exit 2
fi

lastBackupDateString=$(grep 'Time (end):' "$statusfile" | sed -e 's/Time (end):\s\+//g')
lastBackupDate=$(date -d "${lastBackupDateString}" "+%s" )

diff=$((currentDate - lastBackupDate))

((h=diff/3600))
((m=(diff%3600)/60))
((s=diff%60))
diff_time=$(printf "Last backup %02dh %02dm %02ds ago." ${h} ${m} ${s})

if [ "${diff}" -gt "$((critical * 60 * 60))" ]; then
  # this cert is has already expired! return critical status.
  printf "CRITICAL - No backup in over %s hours! %s\n" "$critical" "$diff_time"
  exit 2
elif [ "${diff}" -gt "$((warning * 60 * 60))" ]; then
  # this cert is expiring within the warning threshold. return warning status.
  printf "WARNING - No backup in over %s hours! %s\n" "$warning" "$diff_time"
  exit 1
fi

printf "OK - Backed up within the last %s hours. %s\n" "$warning" "$diff_time"
exit 0
