#!/bin/bash

while getopts "s:n:i:w:c:" opts; do
  case "${opts}" in
    s) sensor=("${OPTARG}");;
    n) name=("${OPTARG}");;
    i) id=("${OPTARG}");;
    w) warn=(${OPTARG});;
    c) crit=(${OPTARG});;
  esac
done

test "${sensor}x" = "x" && sensor=""

status=$(/usr/bin/sensors -f ${sensor} | /bin/grep "${id}")
temp=$(printf "%.0f" $(echo ${status} | \
  /bin/sed -n 's/.*:[ ]\++\([0-9]\+\.[0-9]\+\)°F.*/\1/p'))

if [ "${temp}" -gt "${crit}" ]; then
  echo "CRITICAL: ${name} temperature: ${temp}°F, above critical threshold of ${crit}°F!"
  exit 2
elif [ "${temp}" -gt "${warn}" ]; then
  echo "WARNING: ${name} temperature: ${temp}°F, above warning threshold of ${warn}°F!"
  exit 1
else
  echo "OK: ${name} Temperature: ${temp}°F"
  exit 0
fi
