#!/bin/bash
if grep -q "$1.*/data" /proc/mounts; then
  flags="-d sat,12"
else
  flags=""
fi
/opt/nagios_plugins/regex_command \
  --command "/usr/bin/sudo /usr/sbin/smartctl -A $1 $flags" \
  --regex 'Temp.* (\d+)' --warn $2 --crit $3
exit $?
