#!/bin/bash
if grep -q "$1.*/data" /proc/mounts; then
  flags="-d sat,12"
else
  flags=""
fi
/usr/bin/sudo /usr/sbin/smartctl -H $1 $flags
status=$?
if [[ "${status}" -ne 0 ]]; then
  echo -e "Exit status: $status\n"
  mask=1
  for i in {0..7}; do
    echo "Bit $i: $(((status & mask) && 1))"
    mask=$((mask << 1))
  done
  echo "0: Command line did not parse."
  echo "1: Device open failed, device did not return an IDENTIFY DEVICE structure, or device is in a low-power mode (see '-n' option above)."
  echo "2: Some SMART or other ATA command to the disk failed, or there was a checksum error in a SMART data structure (see '-b' option above)."
  echo "3: SMART status check returned "DISK FAILING"."
  echo "4: We found prefail Attributes <= threshold."
  echo "5: SMART status check returned "DISK OK" but we found that some (usage or prefail) Attributes have been <= threshold at some time in the past."
  echo "6: The device error log contains records of errors."
  echo "7: The device self-test log contains records of errors.  [ATA only] Failed self-tests outdated by a newer successful extended self-test are ignored."
  exit 2
fi
exit 0
