#!/usr/bin/env python
# -*- coding: utf-8 -*-

import optparse
import re
import subprocess


parser = optparse.OptionParser()
parser.add_option('--disk')
parser.add_option('--warn')
parser.add_option('--crit')
(options, _) = parser.parse_args()

cmd = '/usr/bin/sudo /usr/sbin/smartctl -A'.split() + [options.disk]
(stdout, stderr) = subprocess.Popen(cmd,
                                    stdout=subprocess.PIPE,
                                    stderr=subprocess.PIPE).communicate()
result = re.findall(r'Temp.* (\d+)', stdout)
temp = float(result[0])
temp = (1.8 * temp) + 32
units = '°F'

if temp > float(options.crit):
  prefix = 'CRITICAL:'
  ret = 2
elif temp > float(options.warn):
  prefix = 'WARNING:'
  ret = 1
else:
  prefix = 'OK:'
  ret = 0

print '%s Temperature: %0.1f%s' % (prefix, temp, units)
exit(ret)
